# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fb388679cc9adb8ca246c3236dddae9e2dbebf29e12b481246bc8525f69aad9f36303f3b6d2e47df62733a1dd804aca067db609b19a804eaee6d2a78c6364c0

test:
  secret_key_base: cb0682cc159ad50ebd892757f8664b7d40a4df5988ba033696ac5cdb3a60925539d35860265db38f1e1296560f92c70c605799b118f6450dc86fb1e9c92f7417

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
